version: '3'

services:
  redis:
    image: redis:6.2
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
